kind: pipeline
type: docker
name: default

steps:
- name: build
  image: %%{GolangDevImage}:1-alpine
  pull: always
  settings:
    build_script: build.sh

- name: scan
  image: %%{NcicdDockerRepo}/cicd/nancy:latest
  pull: always
  failure: ignore
  depends_on:
  - build

- name: create-image
  image: %%{DroneDockerImage}
  settings:
    repo: %%{NcicdDockerRepo}/cicd/drone-docker-buildx
    dockerfile: Dockerfile.ysg9
    tags:
    - latest
  depends_on:
  - scan

